version: "3.8"

services:
  module:
    depends_on:
      - postgres
    build:
      context: ./analytics-sdk
      target: development
    volumes:
      - ./analytics-sdk:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

  dashboard:
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    build:
      context: ./analytics-website
      target: development
    volumes:
      - ./analytics-website:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.nuxt
    ports:
      - "3001:3000"


  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-analytics:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
volumes:
    postgres-analytics: