version: "3.8"

services:
  nuxt:
    depends_on:
      - postgres
    build:
      context: ./web
      target: development
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"

  nuxt-analytics:
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    build:
      context: ./analytics-website
      target: development
    volumes:
      - ./analytics-website:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3000"


  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-analytics:/var/lib/postgresql/data

volumes:
    postgres-analytics: